sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 4
  - 6
matrix:
  fast_finish: true
env:
  global:
    - BUILD_LEADER_ID=2
script: npm run travis
before_install:
  - npm i -g npm@^2.0.0
before_script:
  - npm prune
after_success:
  - npm install -g npx
  - npx -p node@8 npm run semantic-release
